notion内の規則に従ったファイル構成に修正
badpuku/pukusapo pull request #8
Opened 2024-10-20 14:18 UTC by sugawara-kouki

## refs
- https://discord.com/channels/1289488779303845921/1289488779907698722/1297458196125974558

## 概要
- 指摘いただいた内容に沿って、ファイルの格納先フォルダを変更しました。  
- また、その他必要になるフォルダのみ`.gitkeep`を使用して作成しております。  

## 重点的にレビューしてほしいところ
- ファイル分けが適切かどうか
- constansもこのような使い方で大丈夫かどうか

## 関連issue
- #7

2024-10-20 14:19 UTC, sugawara-kouki commented
@sena-m09 @SenaMurakami 
レビューをお願いします！

2024-10-21 01:43 UTC, sena-m09 requested changes
2点コメントしたのですが、services 周りの使い方うまく伝えられてないようなので、一旦こちらで PR 作成します。
少々お待ちを〜

2024-10-21 01:43 UTC, sena-m09 commented on app/components/ui/button/LogoutButton.tsx
> +    <button
後ほど、button を shacn/ui を使う形に変更したいですね！
デザイン決まってからの作業になると思いますが、忘れないように TODO コメント残しておいてほしいです〜

2024-10-21 01:43 UTC, sena-m09 commented on app/services/index.ts
> +export * from "./userService";
自分の知識不足だと思いますが、このような使い方をしたことがないのと、見た事がないので質問です。
index.ts にまとめるメリットは何でしょうか？
ファイルが増えるたびに index.ts に足していくの単純に面倒だなと思ったので質問でした！

2024-10-21 01:47 UTC, sugawara-kouki commented on app/components/ui/button/LogoutButton.tsx
> +    <button
shadcn/uiのインストールがまだされていなかったのと、フロント周りはせなさんに作業していただく予定だったので通常のボタン&taiwindcssで実装していました！  
TODOコメだけつけておきます！

2024-10-21 01:50 UTC, sugawara-kouki commented on app/services/index.ts
> +export * from "./userService";
serviceを使用する場合に
```
import authFuga from "./services/authService"
import userFuga from "./services/userService"
```
のように、使うサービスが増えた場合にインポート文が大量発生するので、一つにまとめることで
```
import { authFuga, userFuga } from "./services"
```
というようにまとめられるのがメリットだと思いました。  
index.tsに追加する手間はありますが、見やすいのかなと思っております。  
いかがでしょうか？

2024-10-21 01:56 UTC, sena-m09 commented on app/services/index.ts
> +export * from "./userService";
- 関心の近いものを一つの塊にすれば、インポートが増えるのが防げる
- 関心の遠いものを一つのファイルからインポートすると、何をしているものか追いにくくなる
上記の2点から、 index.ts にまとめるのは避けたいと思いました！

services の中まとめてみるので、それ見て意見欲しい！！
お待ちを〜

2024-10-22 13:20 UTC, sugawara-kouki commented
せなさんのRPまで取り込み完了

2024-10-22 14:33 UTC, sugawara-kouki commented
@sena-m09 @SenaMurakami 
ログアウト処理について、質問です。  
ログアウト画面に対してPOSTし、セッションをクリアしてログイン画面にリダイレクトする。という流れの処理を実装したいと考えています。  
ログアウト画面へのPOST、セッションのクリアまではできていますが、そのあとのログイン画面への遷移をnavigateを使用せずに実装する方法がわからず、詰まってしまっております。  
お手すきで実装方法について、ご教授いただければと思います。

ログアウトボタンコンポーネント
```
import { ROUTES } from "~/constants/routes";
import { useNavigate } from "@remix-run/react";

// TODO:: 本コンポーネントをshadcn/uiを使用して再度作成する
/**
 * ログアウトボタンコンポーネント
 */
const LogoutButton = () => {
  const navigate = useNavigate();
  const handleLogout = async () => {
    // ログアウト画面に対してPOSTする
    const logoutResult = await fetch(`http://localhost:3000${ROUTES.LOGOUT}`, {
      method: "POST",
    });

    // レスポンスの値によってエラーか正常かを判定
    if (!logoutResult.ok) {
      throw new Error("ログアウトに失敗しました。");
    }

    // レスポンスが正常な場合、navigateでログイン画面へ遷移
    // FIXME:: ここもnavigateを使用せずに実装したほうがよさげ??
    navigate(ROUTES.LOGIN);
  };

  return (
    <button
      onClick={handleLogout}
      className="px-4 py-2 bg-red-600 text-white rounded-md shadow-md hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 transition-all duration-300"
    >
      ログアウト
    </button>
  );
};

export default LogoutButton;
```

2024-10-23 00:42 UTC, sena-m09 commented
@sugawara-kouki 

> // レスポンスが正常な場合、navigateでログイン画面へ遷移
> // FIXME:: ここもnavigateを使用せずに実装したほうがよさげ??
> navigate(ROUTES.LOGIN);

ここね？ navigate でいいと思います！
ログアウトをするのは内部の処理なので、fetch や form の submit
ログアウト後にログインページにいくのはあくまでページ遷移だから。みたいなイメージです！
厳格にいうと違うと思いますけど...

2024-10-23 00:44 UTC, k-sugawara7201 commented
@sena-m09 
ありがとうございます！  
では、ログアウト処理`logout/route.tsx`では、正常にログアウトできたかどうか。を返却するように修正して、それを見てからnavigateで遷移させます！

2025-01-26 08:14 UTC, closed without merging